

name: Versioning


on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  version_tagging:
    name: Version and Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          default_bump: false
          github_token: ${{ secrets.PAT_TOKEN }}
